---
type: docker
kind: pipeline
name: build

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

steps:
- name: build
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build . -t musicbot:build-${DRONE_BUILD_NUMBER}

- name: push
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker image tag musicbot:build-${DRONE_BUILD_NUMBER} registry.kamaux.de/musicbot:${DRONE_BRANCH}
  - docker push registry.kamaux.de/musicbot:${DRONE_BRANCH}
  when:
    event:
    - push

- name: cleanup
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - sleep 6
  - docker image rm -f musicbot:build-${DRONE_BUILD_NUMBER}
  - docker image prune -f
  when:
    status:
    - failure
    - success
