type: docker
kind: pipeline
name: build

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: env
  host:
    path: /home/environment/musicbot.env

steps:
- name: build
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build ./frontend -t musicbot-frontend:latest

- name: deploy
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: env
    path: /tmp/env
  commands:
  - docker stop musicbot-frontend || true
  - docker rm musicbot-frontend || true
  - docker run -d --name musicbot-frontend --env-file /tmp/env --network nginx --restart unless-stopped musicbot-frontend:latest
  # when:
  #   event:
  #   - promote
  #   target:
  #   - production
