
services:

  frontend:
    build: ./frontend
    restart: always
    # ports:
    # TODO

  backend:
    build: ./backend
    restart: always
    ports:
    - 3000:3000
    

  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    # volumes:
  # - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/

  spotify-lyrics-api:
    image: spotify-lyrics-api
    build:
      dockerfile: spotify-lyrics-api.Dockerfile
      no_cache: true
    restart: always
    ports:
    - 8000:8000
    environment:
      SP_DC: ${SP_DC}
    stop_signal: SIGINT
