
networks:
  default:
    external:
      name: nginx

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    # ports:
  # - 80:80

  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
    - 3000:3000
    env_file: backend/.env
    depends_on:
    - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
    - ./mongodb:/data/db

  mongo-ui:
    container_name: mongo-ui
    image: mongo-express
    restart: always
    ports:
    - 81:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/

  lyrics-api:
    container_name: lyrics-api
    image: spotify-lyrics-api
    build:
      context: .
      dockerfile: spotify-lyrics-api.Dockerfile
      # no_cache: true
    restart: always
    ports:
    - 8000:8000
    # environment:
    #   SP_DC: ${SP_DC}
    env_file:
    - backend/.env
    stop_signal: SIGINT
